#name: drums_material
#
#####network#####
#network: material
#database_name: nerf/drums
#mesh: data/meshes/drums_shape-300000.ply
#is_nerf: true
#
#reg_diffuse_light: true
#reg_diffuse_light_lambda: 0.15
#reg_mat: true
#shader_cfg:
#  diffuse_sample_num: 256
#  specular_sample_num: 512
#  outer_light_version: direction
#  light_exp_max: 5.0
#  inner_light_exp_max: 5.0
#  human_lights: false
#  # Here should have same value as the one in the main config file
#  shading_feature_num: 256
#  num_viewdir_freqs: 0 #6
#
#######loss######
#loss: ['nerf_render','mat_reg']
#val_metric: ['mat_render']
#key_metric_name: psnr
#
#####dataset#####
#train_dataset_type: dummy
#dataset_dir: data/nerf_synthetic
#train_dataset_cfg:
#  database_name: nerf/drums
#  dataset_dir: data/nerf_synthetic
#val_set_list:
#  -
#    name: val
#    type: dummy
#    cfg:
#      database_name: nerf/drums
#      dataset_dir: data/nerf_synthetic
#
#####trainier####
#optimizer_type: adam
#lr_type: warm_up_cos
#lr_cfg:
#  end_warm: 1000
#  end_iter: 100000
#total_step: 100000
#val_interval: 1000
#save_interval: 1000
#train_log_step: 10
#
##################from pointnerf#################
##############!/bin/bash
#nrCheckpoint: "/home/pointnerf/checkpoints"
#nrDataRoot: "/home/pointnerf/data_src"
#scan: "drums"
#
#load_points: 1
#feat_grad: 1
#conf_grad: 1
#dir_grad: 1
#color_grad: 1
#vox_res: 320
#normview: 0
#prune_thresh: -1
#prune_iter: 10000
#prune_max_iter: 30001
#
#feedforward: 0
#ref_vid: 0
#bgmodel: "no" #"plane"
#depth_occ: 1
#depth_vid: "0"
#trgt_id: 0
#manual_depth_view: 1
#init_view_num: 3
#pre_d_est: "/home/pointnerf/checkpoints/MVSNet/model_000014.ckpt"
#manual_std_depth: 0.0
#depth_conf_thresh: 0.8
#appr_feature_str0: ['imgfeat_0_0123', 'dir_0', 'point_conf']
#point_conf_mode: "1" # 0 for only at features, 1 for multi at weight
#point_dir_mode: "0" # 0 for only at features, 1 for color branch
#point_color_mode: "1" # 0 for only at features, 1 for color branch
#default_conf: 0.15
#
#agg_feat_xyz_mode: "None"
#agg_alpha_xyz_mode: "None"
#agg_color_xyz_mode: "None"
#feature_init_method: "rand" #"rand" # "zeros"
#agg_axis_weight: [ 1., 1., 1.]
## Here changed this one from 20 to 0 to use world coordinates instead of perspective ones
#agg_dist_pers: 0
#radius_limit_scale: 4
#depth_limit_scale: 0
#alpha_range: 0
#
#vscale: [ 2, 2, 2 ]
#kernel_size: [ 3, 3, 3 ]
#query_size: [ 3, 3, 3 ]
#vsize: [ 0.004, 0.004, 0.004 ] #" 0.005 0.005 0.005 "
#wcoord_query: 1
#z_depth_dim: 400
#max_o: 400000 #2000000
#ranges: [ -1.126, -0.746, -0.492, 1.122, 0.962, 0.939 ]
#SR: 80
#K: 8
#P: 10 #120
#NN: 2
#
#act_type: "LeakyReLU"
#
#agg_intrp_order: 2
#agg_distance_kernel: "linear" #"avg" #"feat_intrp"
#weight_xyz_freq: 2
#weight_feat_dim: 8
#
#point_features_dim: 32
#shpnt_jitter: "uniform" #"uniform" # uniform gaussian
#
#which_agg_model: "viewmlp"
#apply_pnt_mask: 1
#shading_feature_mlp_layer0: 1 #2
#shading_feature_mlp_layer1: 2 #2
#shading_feature_mlp_layer2: 0 #1
#shading_feature_mlp_layer3: 2 #1
#shading_alpha_mlp_layer: 1
#shading_color_mlp_layer: 4
#shading_feature_num: 256
#dist_xyz_freq: 5
#num_feat_freqs: 3
#dist_xyz_deno: 0
#
#raydist_mode_unit: 1
#dataset_name: 'nerf_synth360_ft'
#pin_data_in_memory: 1
#model: 'mvs_points_volumetric'
#near_plane: 2.0
#far_plane: 6.0
#which_ray_generation: 'near_far_linear' #'nerf_near_far_linear' #
#domain_size: '1'
#dir_norm: 0
#
#which_tonemap_func: "off" #"gamma" #
#which_render_func: 'radiance'
#which_blend_func: 'alpha'
#out_channels: 4
#
#num_pos_freqs: 10
#num_viewdir_freqs: 0 #6
#
#random_sample: 'random'
#random_sample_size: 70 #94 #48 # 32 * 32 :  1024
#batch_size: 1
#plr: 0.002
#lr: 0.0005 # 0.0005 #0.00015
#lr_policy: "iter_exponential_decay"
#lr_decay_iters: 1000000
#lr_decay_exp: 0.1
#
#
#gpu_ids: '0'
#checkpoints_dir: "/home/pointnerf/checkpoints/col_nerfsynth/"
#resume_dir: "/home/pointnerf/checkpoints/init/dtu_dgt_d012_img0123_conf_agg2_32_dirclr20"
#resume_iter: "best"
#
#save_iter_freq: 10000
#save_point_freq: 10000 #301840 #1
#maximum_step: 200000 #800000
#
#niter: 10000 #1000000
#niter_decay: 10000 #250000
#n_threads: 1
#
#train_and_test: 0 #1
#test_num: 10
#test_freq: 10000 #1200 #1200 #30184 #30184 #50000
#print_freq: 40
#test_num_step: 10
#
#
#far_thresh: -1 #0.005
#prob_freq: 10001 #10000 #2000 #1000 is bad #10001
#prob_num_step: 15
#prob_thresh: 0.7
#prob_mul: 0.4
#prob_kernel_size: [ 3, 3, 3, 1, 1, 1 ]
#prob_tiers: [ 100000, 160000 ]
#
#
#zero_epsilon: 1e-3
#
#visual_items: [coarse_raycolor gt_image ]
#zero_one_loss_items: 'conf_coefficient' #regularize background to be either 0 or 1
#zero_one_loss_weights: " 0.0001 "
#sparse_loss_weight: 0
#
#color_loss_weights: [ 1.0, 0.0, 0.0 ]
#color_loss_items: ['ray_masked_coarse_raycolor', 'ray_miss_coarse_raycolor', 'coarse_raycolor']
#test_color_loss_items: ['coarse_raycolor', 'ray_miss_coarse_raycolor', 'ray_masked_coarse_raycolor']
#
#vid: 250000
#
#bg_color: "white" #"0.0,0.0,0.0,1.0,1.0,1.0"
#split: "train"
#data_root: "/home/NeRO/data/nerf_synthetic"
## Here I am not sure about this because they did not put it on the main config file but I think it is the same as the one in the other config files
#full_comb: 1

name: drums_material

####network#####
network: material
database_name: nerf/drums
mesh: data/meshes/drums_shape-300000.ply
is_nerf: true
anisotropy: true
max_n_exp: 20
max_alpha_exp: 10

reg_diffuse_light: true
reg_diffuse_light_lambda: 0.1
reg_mat: false
shader_cfg:
  diffuse_sample_num: 1024
  specular_sample_num: 2048
  outer_light_version: direction
  light_exp_max: 20
  inner_light_exp_max: 20
  human_lights: false
  # Here should have same value as the one in the main config file
  shading_feature_num: 256
  num_viewdir_freqs: 0 #6

######loss######
loss: ['nerf_render','mat_reg']
val_metric: ['mat_render']
key_metric_name: psnr

####dataset#####
train_dataset_type: dummy
dataset_dir: data/nerf_synthetic
train_dataset_cfg:
  database_name: nerf/drums
  dataset_dir: data/nerf_synthetic
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: nerf/drums
      dataset_dir: data/nerf_synthetic

####trainier####
optimizer_type: adam
lr_type: warm_up_cos
lr_cfg:
  end_warm: 1000
  end_iter: 100000
total_step: 100000
val_interval: 1000
save_interval: 1000
train_log_step: 10

#################from pointnerf#################
#############!/bin/bash
nrCheckpoint: "/home/pointnerf/checkpoints"
nrDataRoot: "/home/pointnerf/data_src"
scan: "drums"

load_points: 1
feat_grad: 1
conf_grad: 1
dir_grad: 1
color_grad: 1
vox_res: 320
normview: 0
prune_thresh: -1
prune_iter: 10000
prune_max_iter: 30001

feedforward: 0
ref_vid: 0
bgmodel: "no" #"plane"
depth_occ: 1
depth_vid: "0"
trgt_id: 0
manual_depth_view: 1
init_view_num: 3

pre_d_est: "/home/pointnerf/checkpoints/MVSNet/model_000014.ckpt"
manual_std_depth: 0.0
depth_conf_thresh: 0.8
appr_feature_str0: ['imgfeat_0_0123', 'dir_0', 'point_conf']
point_conf_mode: "1" # 0 for only at features, 1 for multi at weight
point_dir_mode: "0" # 0 for only at features, 1 for color branch
point_color_mode: "1" # 0 for only at features, 1 for color branch
default_conf: 0.15

agg_feat_xyz_mode: "None"
agg_alpha_xyz_mode: "None"
agg_color_xyz_mode: "None"
feature_init_method: "rand" #"rand" # "zeros"
agg_axis_weight: [ 1., 1., 1.]
# Here changed this one from 20 to 0 to use world coordinates instead of perspective ones
agg_dist_pers: 0
radius_limit_scale: 4
depth_limit_scale: 0
alpha_range: 0

vscale: [ 2, 2, 2 ]
kernel_size: [ 3, 3, 3 ]
query_size: [ 3, 3, 3 ]
vsize: [ 0.004, 0.004, 0.004 ] #" 0.005 0.005 0.005 "
wcoord_query: 1
z_depth_dim: 400
max_o: 400000 #2000000
ranges: [ -1.126, -0.746, -0.492, 1.122, 0.962, 0.939 ]
SR: 80
K: 8
P: 10 #120
NN: 2

act_type: "LeakyReLU"

agg_intrp_order: 2
agg_distance_kernel: "linear" #"avg" #"feat_intrp"
weight_xyz_freq: 2
weight_feat_dim: 8

point_features_dim: 32
shpnt_jitter: "uniform" #"uniform" # uniform gaussian

which_agg_model: "viewmlp"
apply_pnt_mask: 1
shading_feature_mlp_layer0: 1 #2
shading_feature_mlp_layer1: 2 #2
shading_feature_mlp_layer2: 0 #1
shading_feature_mlp_layer3: 2 #1
shading_alpha_mlp_layer: 1
shading_color_mlp_layer: 4
shading_feature_num: 256
dist_xyz_freq: 5
num_feat_freqs: 3
dist_xyz_deno: 0

raydist_mode_unit: 1
dataset_name: 'nerf_synth360_ft'
pin_data_in_memory: 1
model: 'mvs_points_volumetric'
near_plane: 2.0
far_plane: 6.0
which_ray_generation: 'near_far_linear' #'nerf_near_far_linear' #
domain_size: '1'
dir_norm: 0

which_tonemap_func: "off" #"gamma" #
which_render_func: 'radiance'
which_blend_func: 'alpha'
out_channels: 4

num_pos_freqs: 10
num_viewdir_freqs: 0 #6

random_sample: 'random'
random_sample_size: 70 #94 #48 # 32 * 32 :  1024
batch_size: 1
plr: 0.002
lr: 0.0005 # 0.0005 #0.00015
lr_policy: "iter_exponential_decay"
lr_decay_iters: 1000000
lr_decay_exp: 0.1


gpu_ids: '0'
checkpoints_dir: "/home/pointnerf/checkpoints/col_nerfsynth/"
resume_dir: "/home/pointnerf/checkpoints/init/dtu_dgt_d012_img0123_conf_agg2_32_dirclr20"
resume_iter: "best"

save_iter_freq: 10000
save_point_freq: 10000 #301840 #1
maximum_step: 200000 #800000

niter: 10000 #1000000
niter_decay: 10000 #250000
n_threads: 1

train_and_test: 0 #1
test_num: 10
test_freq: 10000 #1200 #1200 #30184 #30184 #50000
print_freq: 40
test_num_step: 10


far_thresh: -1 #0.005
prob_freq: 10001 #10000 #2000 #1000 is bad #10001
prob_num_step: 15
prob_thresh: 0.7
prob_mul: 0.4
prob_kernel_size: [ 3, 3, 3, 1, 1, 1 ]
prob_tiers: [ 100000, 160000 ]


zero_epsilon: 1e-3

visual_items: [coarse_raycolor gt_image ]
zero_one_loss_items: 'conf_coefficient' #regularize background to be either 0 or 1
zero_one_loss_weights: " 0.0001 "
sparse_loss_weight: 0

color_loss_weights: [ 1.0, 0.0, 0.0 ]
color_loss_items: ['ray_masked_coarse_raycolor', 'ray_miss_coarse_raycolor', 'coarse_raycolor']
test_color_loss_items: ['coarse_raycolor', 'ray_miss_coarse_raycolor', 'ray_masked_coarse_raycolor']

vid: 250000

bg_color: "white" #"0.0,0.0,0.0,1.0,1.0,1.0"
split: "train"
data_root: "/home/NeRO/data/nerf_synthetic"
# Here I am not sure about this because they did not put it on the main config file but I think it is the same as the one in the other config files
full_comb: 1